# Generated by Django 3.0.3 on 2020-08-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIntroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=256)),
                ('quotes', models.TextField(max_length=256)),
                ('introduction', models.TextField(max_length=256)),
                ('course_pic', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('graduation', models.CharField(max_length=30)),
                ('experience', models.TextField(max_length=50)),
                ('photo', models.ImageField(upload_to='member')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=20)),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('roll_number', models.PositiveIntegerField()),
                ('trade', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=256)),
                ('curriculum', models.TextField(max_length=1500)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='myapp.CourseIntroduction')),
            ],
        ),
    ]
